header:
  license:
    content: |
      Copyright (c) 2024-2025 Datalayer, Inc.

      BSD 3-Clause License


  paths-ignore:
    - '**/*.ipynb'
    - '**/*.json'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/.*'
    - 'docs/**/*'
    - 'LICENSE'

  comment: on-failure